### ISSUE TITLE
HTTP-UA-Parser-0.006: Tests started to fail

### ISSUE THREAD

**Issue by eserte** [ua-parser/uap-perl#5]
See http://matrix.cpantesters.org/?dist=HTTP-UA-Parser%200.006;reports=1#sl=7,1

I suspect this could be caused by https://github.com/ua-parser/uap-core/commit/aad0412268f877ff9d5e806d2ac0a7256210a72b

**Comment by eserte** [comment]
(It passes only if the test files could not be fetched, which could be the case if LWP::Protocol::https is not installed or if there's a network problem)

**Comment by mamod** [comment]
I'm really sorry for this long delay response, this should be fixed now. thank you.
